### ISSUE TITLE
https://claim-tax-benefits.azurewebsites.net/confirm-income

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/cra-claim-tax-benefits#537]
This page should give a different amount for people who are 65 or older, but when I tried using that age  it was the 12K amount. For 65 and older, 

Please replace first line with:
If your income from all sources is $19,564 or more:

Please change last line to:
Check this box to confirm you income from all sources was less than $19,564 in 2019

Thanks!

**Comment by katedee** [comment]
Hi!

So this content is in place, it's just that our current age check validates against the date of birth input, versus the yes/no answer via a `is65()` function. I'm wondering, @pcraig3 , if we should now update this to instead look at the value put in for `ageYesNo`?

**Comment by pcraig3** [comment]
Hello, probably should weigh in here. 

I know developers aren't supposed to say this, but this is actually the intended behaviour.

@katedee, there was a bug we were seeing earlier in that [the `yesNoAge` amount wasn't being preserved](https://trello.com/c/59LFd1UF/269-s-%F0%9F%95%B7income-amount-not-preserved-properly). The reason for it turned out to be that when you make it through the login screens, [the `session.login` values are lost](https://github.com/cds-snc/cra-claim-tax-benefits/blob/master/routes/login/login.controller.js#L174), so the `ageYesNo` amount gets reset.

But then, thinking it over, this is totally okay for us. It's not actually correct to take their answer to the initial Yes/No eligibility question and use it to make decisions later in the application. When they are going through the eligibility questions, we have no information about them: we take it on faith that they are 65 or not. 

Once they are in the application, we have their date of birth from the CRA, which is what we should be using to make decisions after they've logged in. See the explanation in this PR, where it went in: https://github.com/cds-snc/cra-claim-tax-benefits/pull/449

Someone who says they are 65 may not be, and vice-versa.

What this means for our app though (since we only have one user) is that we can _never_ see the other amount — or the senior transit credit. 

I think we have 4 options. 

1. We could do nothing and have the same behaviour as now
2. We could change the birth date so that all the pages would show up
3. We could add a second user, so there are 2 different flows
4. We could make the Senior Transit Credit check and the Confirm Income check reliant on `ageYesNo`, although this would not what we would do in the real product.

@YedidaZalik, @ClementineHahn, @brianhendrick1 do you have thoughts?

**Comment by YedidaZalik** [comment]
I don't have an opinion on this - I defer to the group :)

**Comment by brianhendrick1** [comment]
I think option 3 is the best way to show the journey for people 65 and above. 

Definitely not option 4.

**Comment by ClementineHahn** [comment]
What option 3 would represent as size of work ? if it is reasonable amount of work (done by Wednesday lets say) then i agree with Brian

**Comment by pcraig3** [comment]
Let's go with option 3 then. 

@katedee says she will add one more potential user to the app that we can log in with.

```
SIN: 435 073 143 (don't use the one in the PDF)
Name: Alex Janvier
Date of birth: March 3, 1947
Address: 144 Steel St, Barrie, ON
Postal code: L4M 2G2
Marital status: Single
```
